function showUi = showUi(varargin)
% showUi MATLAB code for showUi.fig
%      showUi, by itself, creates a new showUi or raises the existing
%      singleton*.
%
%      H = showUi returns the handle to a new showUi or the handle to
%      the existing singleton*.
%
%      showUi('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in showUi.M with the given input arguments.
%
%      showUi('Property','Value',...) creates a new showUi or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before showUi_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to showUi_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help showUi

% Last Modified by GUIDE v2.5 07-Oct-2014 16:04:02

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @showUi_OpeningFcn, ...
                   'gui_OutputFcn',  @showUi_OutputFcn, ...
                   'gui_LayoutFcn',  @showUi_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT

% --- Executes just before showUi is made visible.
function showUi_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to showUi (see VARARGIN)

% Choose default command line output for showUi
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes showUi wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = showUi_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;

function responseParams_a_edit_Callback(hObject, eventdata, handles)
% hObject    handle to responseParams_a_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of responseParams_a_edit as text
%        str2double(get(hObject,'String')) returns contents of responseParams_a_edit as a double

% --- Executes during object creation, after setting all properties.
function responseParams_a_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to responseParams_a_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


function responseParams_k_edit_Callback(hObject, eventdata, handles)
% hObject    handle to responseParams_k_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of responseParams_k_edit as text
%        str2double(get(hObject,'String')) returns contents of responseParams_k_edit as a double

% --- Executes during object creation, after setting all properties.
function responseParams_k_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to responseParams_k_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function responseParams_dt_edit_Callback(hObject, eventdata, handles)
% hObject    handle to responseParams_th_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of responseParams_dt_edit as text
%        str2double(get(hObject,'String')) returns contents of responseParams_dt_edit as a double


% --- Executes during object creation, after setting all properties.
function responseParams_dt_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to responseParams_dt_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function responseParams_tnd_edit_Callback(hObject, eventdata, handles)
% hObject    handle to responseParams_tnd_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of responseParams_tnd_edit as text
%        str2double(get(hObject,'String')) returns contents of responseParams_tnd_edit as a double


% --- Executes during object creation, after setting all properties.
function responseParams_tnd_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to responseParams_tnd_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function simulationParam_trialCount_edit_Callback(hObject, eventdata, handles)
% hObject    handle to simulationParam_trialCount_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of simulationParam_trialCount_edit as text
%        str2double(get(hObject,'String')) returns contents of 
%        simulationParam_trialCount_edit as a double

% --- Executes during object creation, after setting all properties.
function simulationParam_trialCount_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to simulationParam_trialCount_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


function taskParams_c_edit_Callback(hObject, eventdata, handles)
% hObject    handle to taskParams_c_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of taskParams_c_edit as text
%        str2double(get(hObject,'String')) returns contents of taskParams_c_edit as a double

% --- Executes during object creation, after setting all properties.
function taskParams_c_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to taskParams_c_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


function responseParams_z_edit_Callback(hObject, eventdata, handles)
% hObject    handle to responseParams_z_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of responseParams_z_edit as text
%        str2double(get(hObject,'String')) returns contents of responseParams_z_edit as a double

% --- Executes during object creation, after setting all properties.
function responseParams_z_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to responseParams_z_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function outcomeParams_pCh1_edit_Callback(hObject, eventdata, handles)
% hObject    handle to outcomeParams_pCh1_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of outcomeParams_pCh1_edit as text
%        str2double(get(hObject,'String')) returns contents of outcomeParams_pCh1_edit as a double

% --- Executes during object creation, after setting all properties.
function outcomeParams_pCh1_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to outcomeParams_pCh1_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


function outcomeParams_meanRT_edit_Callback(hObject, eventdata, handles)
% hObject    handle to outcomeParams_meanRT_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of outcomeParams_meanRT_edit as text
%        str2double(get(hObject,'String')) returns contents of outcomeParams_meanRT_edit as a double

% --- Executes during object creation, after setting all properties.
function outcomeParams_meanRT_edit_CreateFcn(hObject, eventdata, handles)
% hObject    handle to outcomeParams_meanRT_edit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

% --- Executes on button press in run_button.
function run_button_Callback(hObject, eventdata, handles)
% hObject    handle to run_button (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get user input from  GUI
params.a = str2num(get(handles.responseParams_a_edit,'String'));
params.z = str2num(get(handles.responseParams_z_edit,'String'));
params.k = str2num(get(handles.responseParams_k_edit,'String'));
params.dt = str2num(get(handles.responseParams_dt_edit,'String'));
params.tnd = str2num(get(handles.responseParams_tnd_edit,'String'));
params.c = str2num(get(handles.taskParams_c_edit,'String'));
params.trialCount = str2num(get(handles.simulationParams_trialCount_edit,'String'));

choices = simulateChoicesFaster(params);
choiceSummary = summarizeChoices(choices, params);

set(handles.display_choicesTable, 'data', table2cell(choiceSummary));

% nBins = params.trialCount/10;
% histogram(handles.display_hist1, choices(choices(:,1)==1,2), nBins);
% ylim([0 60])
% hold on;
% histogram(handles.histogram1_neg, choices(choices(:,1)==-1,2), nBins);
% set(handles.histogram1_neg, 'XAxisLocation', 'Top', 'YDir', 'Reverse')

nBins = params.trialCount/10;
a(1) = histogram(handles.display_hist1, choices(choices(:,1)==1,2), nBins);
ymode = ylim('mode');
a(2) = histogram(handles.histogram1_neg, choices(choices(:,1)==-1,2), nBins);

set(handles.histogram1_neg, 'XAxisLocation', 'Top', 'YDir', 'Reverse', 'XTickLabel',[]);

set(a(1),'facecolor','k','edgecolor','k');
set(a(2),'facecolor','k','edgecolor','k');
linkaxes([handles.display_hist1, handles.histogram1_neg], 'xy');


% --- If Enable == 'on', executes on mouse press in 5 pixel border.
% --- Otherwise, executes on mouse press in 5 pixel border or over run_button.
function run_button_ButtonDownFcn(hObject, eventdata, handles)
% hObject    handle to run_button (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Creates and returns a handle to the GUI figure. 
function h1 = showUi_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

%%%%%%%%%%%%%%%%%%%%%%%%%
% LAYOUT PARAMS

layout.label.right = 1.8;
layout.label.height = 1.65;
layout.label.width = 8;

layout.edit.left = 12;

layout.edit.vgap = 2.3;
layout.a.bottom = 36;
layout.z.bottom = layout.a.bottom - layout.edit.vgap;
layout.k.bottom = layout.a.bottom - 2 * layout.edit.vgap;
layout.dt.bottom = layout.a.bottom - 3 * layout.edit.vgap;
layout.tnd.bottom = layout.a.bottom - 4 * layout.edit.vgap;


layout.hist.left = 5;
layout.hist.width = 81;
layout.hist.height = 10;
layout.table.height = 4.6;
layout.hist2.bottom = 2; 
layout.hist1.bottom = layout.hist2.bottom * 2 + layout.hist.height;
layout.table.bottom = layout.hist1.bottom + layout.hist.height + layout.hist2.bottom;

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load showUi.mat

%%%%%%%%%%%%%%%%%%%%%
% Parent figure

appdata = [];
appdata.GUIDEOptions = mat{1};
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Units','characters',...
'Position',[100 20 132 42],...
'Visible','on',...
'Color',[1 1 1],...
'CloseRequestFcn',get(0,'defaultfigureCloseRequestFcn'),...
'CurrentAxesMode','manual',...
'CurrentObjectMode','manual',...
'CurrentPointMode','manual',...
'SelectionTypeMode','manual',...
'ResizeFcn',blanks(0),...
'IntegerHandle','off',...
'NextPlot',get(0,'defaultfigureNextPlot'),...
'Alphamap',get(0,'defaultfigureAlphamap'),...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'WindowButtonDownFcn',blanks(0),...
'WindowButtonUpFcn',blanks(0),...
'WindowButtonMotionFcn',blanks(0),...
'WindowScrollWheelFcn',blanks(0),...
'WindowKeyPressFcn',blanks(0),...
'WindowKeyReleaseFcn',blanks(0),...
'MenuBar','none',...
'ToolBar',get(0,'defaultfigureToolBar'),...
'Pointer',get(0,'defaultfigurePointer'),...
'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
'Name','paramGUI1',...
'NumberTitle','off',...
'WindowStyle',get(0,'defaultfigureWindowStyle'),...
'DockControls',get(0,'defaultfigureDockControls'),...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',get(0,'defaultfigurePaperSize'),...
'PaperType',get(0,'defaultfigurePaperType'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
'ScreenPixelsPerInchMode','manual',...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'ChildrenMode','manual',...
'HandleVisibility','callback',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','figure1',...
'UserData',[]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RESPONSE PARAMS

appdata = [];
appdata.lastValidTag = 'text_responseParams';

h4 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','Response',...
'Style','text',...
'Position',[1.16666666666667 38 20.5 1.25],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text_responseParams',...
'FontSize',11,...
'FontName','HelveticaNeue',...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

%%%%%%%%%%%%%%%%%%%%%%%%%
% PARAMS.A
appdata = [];
appdata.lastValidTag = 'responseParams_a_label';

h6 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','A',...
'Style','text',...
'Position',[layout.label.right layout.a.bottom layout.label.width layout.label.height],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','responseParams_a_label',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'responseParams_a_edit';

h7 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String', '1',...
'Style','edit',...
'Position',[layout.edit.left layout.a.bottom 9.83333333333333 1.83333333333334],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('responseParams_a_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('responseParams_a_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','responseParams_a_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PARAMS Z

appdata = [];
appdata.lastValidTag = 'responseParams_z_label';

h23 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','z',...
'Style','text',...
'Position',[layout.label.right layout.z.bottom layout.label.width layout.label.height],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','responseParams_z_label',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'responseParams_z_edit';

h24 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','0',...
'Style','edit',...
'Position',[layout.edit.left layout.z.bottom 9.83333333333333 1.83333333333334],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('responseParams_z_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'KeyPressFcn',blanks(0),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('responseParams_z_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','responseParams_z_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');


%%%%%%%%%%%%%%%%%%%%%%%%%
% PARAMS.K
appdata = [];
appdata.lastValidTag = 'responseParams_k_label';

h8 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','k',...
'Style','text',...
'Position',[layout.label.right layout.k.bottom  layout.label.width layout.label.height],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','responseParams_k_label',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'responseParams_k_edit';

h9 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','10',...
'Style','edit',...
'Position',[layout.edit.left layout.k.bottom 9.5 1.83333333333333],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('responseParams_k_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('responseParams_k_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','responseParams_k_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');

%%%%%%%%%%%%%%%%%%%%%%%%%
% PARAMS.DT
appdata = [];
appdata.lastValidTag = 'responseParams_dt_label';

h30 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','dt',...
'Style','text',...
'Position',[layout.label.right layout.dt.bottom layout.label.width layout.label.height],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','responseParams_dt_label',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'responseParams_dt_edit';

h31 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','.005',...
'Style','edit',...
'Position',[layout.edit.left layout.dt.bottom 9.5 1.83333333333333],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('responseParams_dt_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('responseParams_dt_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','responseParams_dt_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');

%%%%%%%%%%%%%%%%%%%%%%%%%
% PARAMS TND

appdata = [];
appdata.lastValidTag = 'responseParam_tnd_label';

h10 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','T(nd)',...
'Style','text',...
'Position',[layout.label.right layout.tnd.bottom  layout.label.width layout.label.height],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','responseParam_tnd_label',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'responseParams_tnd_edit';

h11 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','1',...
'Style','edit',...
'Position',[layout.edit.left layout.tnd.bottom 9.5 1.83333333333333],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('responseParams_tnd_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'KeyPressFcn',blanks(0),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('responseParams_tnd_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','responseParams_tnd_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TASK PARAMS
%

appdata = [];
appdata.lastValidTag = 'taskParam_label';

h5 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','Task',...
'Style','text',...
'Position',[layout.label.right 25 19 1.41666666666667],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','taskParam_label',...
'FontSize',11,...
'FontName','HelveticaNeue',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


%%%%%%%%%%%%%%%%%%%%%%%%%
% PARAMS C

appdata = [];
appdata.lastValidTag = 'taskParams_c_label';

h2 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','C',...
'Style','text',...
'Position',[layout.label.right 22.33 8 1.8],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'Tag','taskParams_c_label',...
'FontSize',11,...
'FontName','HelveticaNeue',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'taskParams_c_edit';

h15 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','.05',...
'Style','edit',...
'Position',[layout.edit.left 22.4166666666667 9.5 1.83333333333333],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('taskParams_c_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'KeyPressFcn',blanks(0),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('taskParams_c_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','taskParams_c_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SIMULATION PARAMS

appdata = [];
appdata.lastValidTag = 'simulationParams_label';

h12 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','Simulation',...
'Style','text',...
'Position',[layout.label.right 19.1666666666667 20.5 1.25],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','simulationParams_label',...
'FontSize',11,...
'FontName','HelveticaNeue',...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

%%%%%%%%%%%%%%%%%%%%%%%%%
% PARAMS TRIAL COUNT

appdata = [];
appdata.lastValidTag = 'simulationParams_trialCount_label';

h13 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','Trials',...
'Style','text',...
'Position',[layout.label.right 17.3333333333333 8 1.08333333333333],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','simulationParams_trialCount_label',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'simulationParams_trialCount_edit';

h14 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','1000',...
'Style','edit',...
'Position',[11.8333333333333 16.8333333333333 9.83333333333333 1.83333333333333],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('simulationParam_trialCount_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'KeyPressFcn',blanks(0),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('simulationParam_trialCount_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','simulationParams_trialCount_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');


%%%%%%%%%%%%%%%%%%%%%%%%%
% RUN BUTTON

appdata = [];
appdata.lastValidTag = 'run_button';

h90 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Run',...
'Position',[layout.edit.left 6.58333333333333 11.6666666666667 1.75],...
'Callback',@(hObject,eventdata)showUi('run_button_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',@(hObject,eventdata)showUi('run_button_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'Tag','run_button',...
'FontSize',11,...
'FontName','HelveticaNeue',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CHART PANEL

appdata = [];
appdata.lastValidTag = 'uipanel1';

h16 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',[0 0 0],...
'ShadowColor',[0 0 0],...
'BorderType','beveledout',...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title','Results',...
'Position',[35 6 90 33],...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',[1 1 1],...
'ResizeFcn',blanks(0),...
'Clipping','off',...
'ChildrenMode','manual',...
'ParentMode','manual',...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','uipanel1',...
'UserData',[],...
'FontSize',11,...
'FontName','HelveticaNeue',...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Axes

appdata = [];
appdata.lastValidTag = 'display_hist1';

h17 = axes(...
'Parent',h16,...
'FontUnits',get(0,'defaultaxesFontUnits'),...
'Units','characters',...
'View',get(0,'defaultaxesView'),...
'CameraMode',get(0,'defaultaxesCameraMode'),...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
'Projection',get(0,'defaultaxesProjection'),...
'AmbientLightColor',get(0,'defaultaxesAmbientLightColor'),...
'Position',[layout.hist.left layout.hist1.bottom layout.hist.width layout.hist.height],...
'ActivePositionProperty','position',...
'LooseInset',[10.465 3.45583333333333 7.6475 2.35625],...
'LooseInsetMode',get(0,'defaultaxesLooseInsetMode'),...
'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
'PlotBoxAspectRatio',[1 0.446153846153846 0.446153846153846],...
'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
'FontName',get(0,'defaultaxesFontName'),...
'FontSize',get(0,'defaultaxesFontSize'),...
'FontAngle',get(0,'defaultaxesFontAngle'),...
'FontWeight',get(0,'defaultaxesFontWeight'),...
'FontSmoothing',get(0,'defaultaxesFontSmoothing'),...
'TickLabelInterpreter',get(0,'defaultaxesTickLabelInterpreter'),...
'XDir',get(0,'defaultaxesXDir'),...
'YDir',get(0,'defaultaxesYDir'),...
'ZDir',get(0,'defaultaxesZDir'),...
'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
'ColorOrderIndex',get(0,'defaultaxesColorOrderIndex'),...
'LineStyleOrder',get(0,'defaultaxesLineStyleOrder'),...
'LineStyleOrderIndex',get(0,'defaultaxesLineStyleOrderIndex'),...
'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
'Layer',get(0,'defaultaxesLayer'),...
'TitleMode','manual',...
'TickLength',get(0,'defaultaxesTickLength'),...
'GridLineStyle',get(0,'defaultaxesGridLineStyle'),...
'MinorGridLineStyle',get(0,'defaultaxesMinorGridLineStyle'),...
'MinorGridColor',get(0,'defaultaxesMinorGridColor'),...
'XRulerMode',get(0,'defaultaxesXRulerMode'),...
'XAxisLocation',get(0,'defaultaxesXAxisLocation'),...
'XTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'XTickMode',get(0,'defaultaxesXTickMode'),...
'XTickLabelRotation',get(0,'defaultaxesXTickLabelRotation'),...
'XLabelMode','manual',...
'XScale',get(0,'defaultaxesXScale'),...
'XTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
'XMinorTick',get(0,'defaultaxesXMinorTick'),...
'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
'YRulerMode',get(0,'defaultaxesYRulerMode'),...
'YAxisLocation',get(0,'defaultaxesYAxisLocation'),...
'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'YTickMode',get(0,'defaultaxesYTickMode'),...
'YTickLabelRotation',get(0,'defaultaxesYTickLabelRotation'),...
'YLabelMode','manual',...
'YScale',get(0,'defaultaxesYScale'),...
'YTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
'YMinorTick',get(0,'defaultaxesYMinorTick'),...
'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
'ZTickLabelRotation',get(0,'defaultaxesZTickLabelRotation'),...
'ZLabelMode','manual',...
'ZScale',get(0,'defaultaxesZScale'),...
'ZMinorTick',get(0,'defaultaxesZMinorTick'),...
'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
'BoxStyle',get(0,'defaultaxesBoxStyle'),...
'LineWidth',get(0,'defaultaxesLineWidth'),...
'Color',get(0,'defaultaxesColor'),...
'Clipping',get(0,'defaultaxesClipping'),...
'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
'NextPlot',get(0,'defaultaxesNextPlot'),...
'SortMethod','childorder',...
'TitleFontWeight',get(0,'defaultaxesTitleFontWeight'),...
'TitleFontSizeMultiplier',get(0,'defaultaxesTitleFontSizeMultiplier'),...
'LabelFontSizeMultiplier',get(0,'defaultaxesLabelFontSizeMultiplier'),...
'ClippingStyle',get(0,'defaultaxesClippingStyle'),...
'XGrid',get(0,'defaultaxesXGrid'),...
'XMinorGrid',get(0,'defaultaxesXMinorGrid'),...
'YGrid',get(0,'defaultaxesYGrid'),...
'YMinorGrid',get(0,'defaultaxesYMinorGrid'),...
'ZGrid',get(0,'defaultaxesZGrid'),...
'ZMinorGrid',get(0,'defaultaxesZMinorGrid'),...
'Box',get(0,'defaultaxesBox'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','display_hist1',...
'UserData',[],...
'SelectedMode','manual',...
'SelectionHighlight',get(0,'defaultaxesSelectionHighlight'),...
'HitTest',get(0,'defaultaxesHitTest'),...
'PickableParts',get(0,'defaultaxesPickableParts'),...
'ChildrenMode','manual',...
'ParentMode','manual',...
'Visible',get(0,'defaultaxesVisible'),...
'HandleVisibility',get(0,'defaultaxesHandleVisibility'));

h18 = get(h17,'title');

set(h18,...
'Parent',h17,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.5 1.01354679802956 0.499999999999998],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','HelveticaNeue',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','bold',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'SelectionHighlight','on',...
'SelectionHighlightMode','auto',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'IsContainer','off',...
'IsContainerMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','Axes Title',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'CreateFcn', {@local_CreateFcn, 'Positive', appdata} );

h19 = get(h17,'xlabel');

set(h19,...
'Parent',h17,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[0.5 -0.0689655172413793 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','HelveticaNeue',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','top',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'SelectionHighlight','on',...
'SelectionHighlightMode','auto',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'IsContainer','off',...
'IsContainerMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h20 = get(h17,'ylabel');

set(h20,...
'Parent',h17,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[-0.0459370707417582 0.5 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',90,...
'RotationMode','auto',...
'FontName','HelveticaNeue',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'SelectionHighlight','on',...
'SelectionHighlightMode','auto',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'IsContainer','off',...
'IsContainerMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


appdata = [];
appdata.lastValidTag = 'histogram1_neg';

histogram1_neg = axes(...
'Parent',h16,...
'FontUnits',get(0,'defaultaxesFontUnits'),...
'Units','characters',...
'View',get(0,'defaultaxesView'),...
'CameraMode',get(0,'defaultaxesCameraMode'),...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
'Projection',get(0,'defaultaxesProjection'),...
'AmbientLightColor',get(0,'defaultaxesAmbientLightColor'),...
'Position',[layout.hist.left layout.hist2.bottom layout.hist.width layout.hist.height],...
'ActivePositionProperty','position',...
'LooseInset',[10.465 3.45583333333333 7.6475 2.35625],...
'LooseInsetMode',get(0,'defaultaxesLooseInsetMode'),...
'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
'PlotBoxAspectRatio',[1 0.446153846153846 0.446153846153846],...
'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
'FontName',get(0,'defaultaxesFontName'),...
'FontSize',get(0,'defaultaxesFontSize'),...
'FontAngle',get(0,'defaultaxesFontAngle'),...
'FontWeight',get(0,'defaultaxesFontWeight'),...
'FontSmoothing',get(0,'defaultaxesFontSmoothing'),...
'TickLabelInterpreter',get(0,'defaultaxesTickLabelInterpreter'),...
'XDir',get(0,'defaultaxesXDir'),...
'YDir',get(0,'defaultaxesYDir'),...
'ZDir','reverse',...
'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
'ColorOrderIndex',get(0,'defaultaxesColorOrderIndex'),...
'LineStyleOrder',get(0,'defaultaxesLineStyleOrder'),...
'LineStyleOrderIndex',get(0,'defaultaxesLineStyleOrderIndex'),...
'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
'Layer',get(0,'defaultaxesLayer'),...
'TitleMode','manual',...
'TickLength',get(0,'defaultaxesTickLength'),...
'GridLineStyle',get(0,'defaultaxesGridLineStyle'),...
'MinorGridLineStyle',get(0,'defaultaxesMinorGridLineStyle'),...
'MinorGridColor',get(0,'defaultaxesMinorGridColor'),...
'XRulerMode',get(0,'defaultaxesXRulerMode'),...
'XAxisLocation','top',...
'XTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'XTickMode',get(0,'defaultaxesXTickMode'),...
'XTickLabelRotation',get(0,'defaultaxesXTickLabelRotation'),...
'XLabelMode','manual',...
'XScale',get(0,'defaultaxesXScale'),...
'XTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
'XMinorTick',get(0,'defaultaxesXMinorTick'),...
'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
'YRulerMode',get(0,'defaultaxesYRulerMode'),...
'YAxisLocation',get(0,'defaultaxesYAxisLocation'),...
'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'YTickMode',get(0,'defaultaxesYTickMode'),...
'YTickLabelRotation',get(0,'defaultaxesYTickLabelRotation'),...
'YLabelMode','manual',...
'YScale',get(0,'defaultaxesYScale'),...
'YTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
'YMinorTick',get(0,'defaultaxesYMinorTick'),...
'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
'ZTickLabelRotation',get(0,'defaultaxesZTickLabelRotation'),...
'ZLabelMode','manual',...
'ZScale',get(0,'defaultaxesZScale'),...
'ZMinorTick',get(0,'defaultaxesZMinorTick'),...
'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
'BoxStyle',get(0,'defaultaxesBoxStyle'),...
'LineWidth',get(0,'defaultaxesLineWidth'),...
'Color',get(0,'defaultaxesColor'),...
'Clipping',get(0,'defaultaxesClipping'),...
'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
'NextPlot',get(0,'defaultaxesNextPlot'),...
'SortMethod','childorder',...
'TitleFontWeight',get(0,'defaultaxesTitleFontWeight'),...
'TitleFontSizeMultiplier',get(0,'defaultaxesTitleFontSizeMultiplier'),...
'LabelFontSizeMultiplier',get(0,'defaultaxesLabelFontSizeMultiplier'),...
'ClippingStyle',get(0,'defaultaxesClippingStyle'),...
'XGrid',get(0,'defaultaxesXGrid'),...
'XMinorGrid',get(0,'defaultaxesXMinorGrid'),...
'YGrid',get(0,'defaultaxesYGrid'),...
'YMinorGrid',get(0,'defaultaxesYMinorGrid'),...
'ZGrid',get(0,'defaultaxesZGrid'),...
'ZMinorGrid',get(0,'defaultaxesZMinorGrid'),...
'Box',get(0,'defaultaxesBox'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','histogram1_neg',...
'UserData',[],...
'SelectedMode','manual',...
'SelectionHighlight',get(0,'defaultaxesSelectionHighlight'),...
'HitTest',get(0,'defaultaxesHitTest'),...
'PickableParts',get(0,'defaultaxesPickableParts'),...
'ChildrenMode','manual',...
'ParentMode','manual',...
'Visible',get(0,'defaultaxesVisible'),...
'HandleVisibility',get(0,'defaultaxesHandleVisibility'));

histogram1_neg_data = get(histogram1_neg,'title');

set(histogram1_neg_data,...
'Parent',histogram1_neg,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.5 1.01354679802956 0.499999999999998],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','HelveticaNeue',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','bold',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'SelectionHighlight','on',...
'SelectionHighlightMode','auto',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'IsContainer','off',...
'IsContainerMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','Axes Title',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'CreateFcn', {@local_CreateFcn, 'Negative', appdata} );

histogram1_neg_x = get(histogram1_neg,'xlabel');

set(histogram1_neg_x,...
'Parent',histogram1_neg,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[0.5 -0.0689655172413793 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','HelveticaNeue',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','top',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'SelectionHighlight','on',...
'SelectionHighlightMode','auto',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'IsContainer','off',...
'IsContainerMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

histogram1_neg_y = get(histogram1_neg,'ylabel');

set(histogram1_neg_y,...
'Parent',histogram1_neg,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[-0.0459370707417582 0.5 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',90,...
'RotationMode','auto',...
'FontName','HelveticaNeue',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'SelectionHighlight','on',...
'SelectionHighlightMode','auto',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'IsContainer','off',...
'IsContainerMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','NumericRuler Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TABLE

appdata = [];
appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension'...
    'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' }...
    {  [4 2] [4 2] 'DataExisting' [1 3] {  blanks(0) blanks(0) } {  blanks(0) blanks(0) blanks(0) blanks(0) } } };
appdata.lastValidTag = 'display_choicesTable';

h22 = uitable(...
'Parent',h16,...
'FontUnits',get(0,'defaultuitableFontUnits'),...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'ColumnName',{  'Count'; 'Frequency'; 'Mean T(d)'},...
'ColumnWidth',{  'auto' 'auto' },...
'RowName',{  'Ch1'; 'Ch2' },...
'Position',[layout.hist.left layout.table.bottom layout.hist.width layout.table.height],...
'ColumnEditable',mat{2},...
'ColumnFormat',{  [] [] },...
'Data',{  blanks(0) blanks(0) blanks(0); blanks(0) blanks(0) blanks(0) },...
'RearrangeableColumns',get(0,'defaultuitableRearrangeableColumns'),...
'RowStriping','off',...
'CellEditCallback',blanks(0),...
'CellSelectionCallback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuitableForegroundColor'),...
'Enable',get(0,'defaultuitableEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuitableVisible'),...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'ParentMode','manual',...
'HandleVisibility',get(0,'defaultuitableHandleVisibility'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','display_choicesTable',...
'UserData',[],...
'FontSize',get(0,'defaultuitableFontSize'),...
'FontName',get(0,'defaultuitableFontName'),...
'FontAngle',get(0,'defaultuitableFontAngle'),...
'FontWeight',get(0,'defaultuitableFontWeight'));

appdata = [];
appdata.lastValidTag = 'outcomeParams_label';

h25 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','Outcome',...
'Style','text',...
'Position',[1.16666666666667 14 20.5 1.25],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','outcomeParams_label',...
'FontSize',11,...
'FontName','HelveticaNeue',...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'outcomeParams_pCh1_label';

h26 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','P(ch1)',...
'Style','text',...
'Position',[layout.label.right 12.0833333333333 8 1.16666666666667],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','outcomeParams_pCh1_label',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'outcomeParams_pCh1_edit';

h27 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','',...
'Style','edit',...
'Position',[layout.edit.left 11.6666666666667 9.83333333333333 1.83333333333333],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('outcomeParams_pCh1_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'KeyPressFcn',blanks(0),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('outcomeParams_pCh1_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','outcomeParams_pCh1_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'outcomeParams_meanRT_label';

h50 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','right',...
'String','Mean RT',...
'Style','text',...
'Position',[layout.label.right 9.58333333333333 8 1.08333333333333],...
'BackgroundColor',[1 1 1],...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','outcomeParams_meanRT_label',...
'FontSize',11,...
'FontName','HelveticaNeue');

appdata = [];
appdata.lastValidTag = 'outcomeParams_meanRT_edit';

h51 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','',...
'Style','edit',...
'Position',[layout.edit.left 9.08333333333333 9.83333333333333 1.83333333333333],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)showUi('outcomeParams_meanRT_edit_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'KeyPressFcn',blanks(0),...
'ParentMode','manual',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)showUi('outcomeParams_meanRT_edit_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'Tag','outcomeParams_meanRT_edit',...
'FontSize',11,...
'FontName','HelveticaNeue');


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % showUi
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % showUi(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % showUi('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % showUi(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI M-file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%     if feature('HGUsingMATLABClasses')
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
%     end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


